// English Translations
const Map<String, String> arAR = {
  'title': "وظّفني",
  "leave_button": "الخروج",
  "leave": "مغادرة التطبيق",
  "leave_message":
      "أنت على وشك مغادرة التطبيق ، هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "cancel": "الغاء",
  "yes": "أجل",
  "map": "الخريطة",
  "job_offers": "عروضات الأعمال",
  "edit_profile": "تعديل",
  "settings": "الاعدادت",
  "aboutApp": "حول التطبيق",
  "termPrivacy": "شروط الخدمة | سياسة الخصوصية",
  "Regular User": "مستخدم عادي",
  "fullName": "الاسم الكامل",
  "birthDay": "تاريخ الميلاد",
  "zodiac": "برجك",
  "save": "حفظ",
  "appLanguage": "لغة التطبيق",
  "appLangDesc": "تغيير لغة التطبيق",
  "Arabic": "Arabic",
  "English": "الانجليزية",
  "darkMode": "الوضع الليلي",
  "home": "الرئيسية",
  "on": "مفعل",
  "off": "غير مفعل",
  "listView": "عرض القائمة",
  "mapView": "عرض الخريطة",
  "HomePageView": "وضع عرض الصفحة الرئيسية",
  "drawerBackgroundColor": "لون خلفية الدرج",
  "clickToChange": "انقر للتغيير",
  "resetDrawerBackgroundColor" :"إعادة تعيين لون خلفية الدرج إلى الافتراضي",
};
