// English Translations
const Map<String, String> enUS = {
  'title': 'Wazefini',
  "leave_button": "Leave",
  "leave": "Leaving the app",
  "leave_message":
      "You are about to leave the app.Are you sure you want to log out ?",
  "cancel": "Cancel",
  "yes": "Yes",
  "map": "Map",
  "job_offers": "Job Offers",
  "edit_profile": "Edit Profile",
  "settings": "Settings",
  "aboutApp": "About the App",
  "termPrivacy": "Term of Service | Privacy Policy",
  "Regular User": "Regular User",
  "fullName": "Full Name",
  "birthDay": "BirthDay",
  "zodiac": "Your Zodiac",
  "save": "Save",
  "appLanguage": "App Language",
  "appLangDesc": "Change app Language",
  "Arabic": "العربية",
  "English": "English",
  "darkMode": "Dark Mode",
  "home": "Home",
  "on": "On",
  "off": "Off",
  "listView" : "List View",
  "mapView":"Map View",
  "HomePageView":"Home Page View Mode : ",
  "drawerBackgroundColor":"Drawer Background Color",
  "clickToChange":"Click to Change",
  "resetDrawerBackgroundColor" :"Reset Drawer Background Color to default",
};
