// English Translations
const Map<String, String> arAR = {
  'title': "وظّفني",
  "leave_button": "الخروج",
  "leave": "مغادرة التطبيق",
  "leave_message":
      "أنت على وشك مغادرة التطبيق ، هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "cancel": "الغاء",
  "yes": "أجل",
  "map": "الخريطة",
  "job_offers": "عروضات الأعمال",
  "edit_profile": "تعديل",
  "settings": "الاعدادت",
  "aboutApp": "حول التطبيق",
  "termPrivacy": "شروط الخدمة | سياسة الخصوصية",
  "Regular User": "مستخدم عادي",
  "fullName": "الاسم الكامل",
  "birthDay": "تاريخ الميلاد",
  "zodiac": "برجك",
  "save": "حفظ",
  "appLanguage": "لغة التطبيق",
  "appLangDesc": "تغيير لغة التطبيق",
  "Arabic": "Arabic",
  "English": "الانجليزية",
  "darkMode": "الوضع الليلي",
  "home": "الرئيسية",
  "on": "مفعل",
  "off": "غير مفعل",
  "listView": "عرض القائمة",
  "mapView": "عرض الخريطة",
  "HomePageView": "وضع عرض الصفحة الرئيسية",
  "drawerBackgroundColor": "لون خلفية القائمة",
  "clickToChange": "انقر للتغيير",
  "resetDrawerBackgroundColor": "إعادة تعيين لون خلفية القائمة إلى الافتراضي",
  "click on": "انقر فوق",
  "to navigate": "للملاحه",
  "last update on": "التحديث الأخير بتاريخ",
  "delete": "حذف",
  "by you": "بواسطتك",
  "profession": "مهنة",
  "Service Provider": "مقدم خدمة",
  "bio": "السيرة الذاتية",
  "am i available ? ": "هل أنا موجود؟",
  "Edit Name": "تعديل الاسم",
  "Edit BirthDay": "تعديل عيد الميلاد",
  "New Bio": "سيرة ذاتية جديدة",
  "Old Bio": "السيرة الذاتية القديمة",
  "App Version": "نسخة التطبيق",
  "aboutAppMessage":
      "فكرة مشروعنا هي تطبيق للهاتف المحمول من شأنه أن يدعم الأشخاص الذين لديهم مهارات مهنية مثل الكهرباء أو الرسام أو النجار ويربطهم بأولئك الذين يحتاجون إلى مثل هذه الخدمات. سيسمح تطبيقنا أيضًا للأشخاص بنشر الوظائف الشاغرة حتى يتمكن المستخدمون من الاستفادة من تطبيقنا للعثور على وظائف في أماكن معينة عبر الإنترنت.",
  "copyRightMessage": "فريق وظّفني © 2021",
  "Select item": "حدد العنصر",
  "Refresh": "تحديث",
  "Reset Filter": " إعادة تعيين الفلتر",
  "Service Provider Bio": "السيرة الذاتية لمقدم الخدمة",
  "Price Range": "نطاق السعر",
  "Reviews": "المراجعات",
  "Add a Review": "إضافة مراجعة",
  "Write a Review": "أكتب مراجعة",
  "Review": "مراجعة",
  "Read Reviews": "قراءة المراجعات",
  "Add Review": "إضافة مراجعة",
  "Filter :": "الفلتر",
  "Found ": "وجد ",
};
