// English Translations
const Map<String, String> enUS = {
  'title': 'Wazefini',
  "leave_button": "Leave",
  "leave": "Leaving the app",
  "leave_message":
      "You are about to leave the app.Are you sure you want to log out ?",
  "cancel": "Cancel",
  "yes": "Yes",
  "map": "Map",
  "job_offers": "Job Offers",
  "edit_profile": "Edit Profile",
  "settings": "Settings",
  "aboutApp": "About the App",
  "termPrivacy": "Term of Service | Privacy Policy",
  "Regular User": "Regular User",
  "fullName": "Full Name",
  "birthDay": "Birthdate",
  "zodiac": "Your Zodiac",
  "save": "Save",
  "appLanguage": "App Language",
  "appLangDesc": "Change app Language",
  "Arabic": "العربية",
  "English": "English",
  "darkMode": "Dark Mode",
  "home": "Home",
  "on": "On",
  "off": "Off",
  "listView": "List View",
  "mapView": "Map View",
  "HomePageView": "Home Page View Mode : ",
  "drawerBackgroundColor": "Drawer Background Color",
  "clickToChange": "Click to Change",
  "resetDrawerBackgroundColor": "Reset Drawer Background Color to default",
  "click on": "Click on",
  "to navigate": "To Navigate !",
  "last update on": "Last Update on",
  "delete": "Delete",
  "by you": "By you",
  "profession": "Profession",
  "Service Provider": "Service Provider",
  "bio": "Bio",
  "am i available ? ": "Am I Available ? ",
  "Edit Name": "Edit Name",
  "Edit BirthDay": "Edit Birthday",
  "New Bio": "New Bio",
  "Old Bio": "Old Bio",
  "App Version": "App Version",
  "aboutAppMessage":
      "Our project idea is a mobile application that will support people who have vocational skills like electric, painter, or carpenter and connect them with those who are in need for such services. Our application will also allow people to post job vacancies so that users can make use of our app to find jobs in certain places online.",
  "copyRightMessage": " Wazefini Team © 2021 ",
  "Select item": "Select item",
  "Refresh": "Refresh",
  "Reset Filter": "Reset Filter",
  "Service Provider Bio": "Service Provider Bio",
  "Price Range": "fees",
  "Reviews": "Reviews",
  "Add a Review": "Add a Review",
  "Write a Review": "Write a Review",
  "Review": "Review",
  "Read Reviews": "Read Reviews",
  "Add Review": "Add Review",
  "Filter :": "Filter :",
  "Found ": "Found ",
};
